### ISSUE TITLE
Images are missing

### ISSUE THREAD

**Issue by mayankshukla91** [embeddedartistry/templates#13]
# Expected Behavior

Images should be displayed on *.md files view.
eg : https://github.com/embeddedartistry/templates/blob/master/documentation/architecture/architecture_view.md

# Current Behavior

images not displayed and not even found when opened in separate tab

![image](https://user-images.githubusercontent.com/10467078/157204443-572384bf-6fe8-47c6-a406-cdc20ec7080e.png)

**Comment by phillipjohnston** [comment]
They aren't real images - just placeholder filenames for the template.
